### ISSUE TITLE
Error when running "node index.js"

### ISSUE THREAD

**Issue by Ultragamer135** [gaelgthomas/first-api-with-node-and-express-example#1]
When i run "node index.js", i get an error that says:

```
/home/elinero/herewecode-docker/first-api/index.js:2
import express from "express";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

```

Please help!

**Comment by gaelgthomas** [comment]
Hello @UsernameNotAvalible,

The error you have is because you didn't specify the following statement in your **`package.json`** file.

```json
  "type": "module"
```

If you want to have an example, you can check the [**`package.json`**](https://github.com/gael-thomas/first-api-with-node-and-express-example/blob/master/package.json) of the repository.

I hope it helps you!
Please let me know if it's working on your side!
